name: Arduino CI

on: push

jobs:
  build:
    strategy:
      matrix:
        board: [BOARD_RUMBA, BOARD_RAMPS, BOARD_SIXI_MEGA, BOARD_CNCV3, BOARD_WEMOS, BOARD_ESP32]
        robot: [POLARGRAPH, TRADITIONALXY, COREXY, ZARPLOTTER, SKYCAM, DELTA, STEWART, ARM3, SIXI, TRADITIONAL6, SCARA]
        # we cannot complie BOARD_TEENSYLU or BOARD_SANGUINOLULU at this time.
        include:
          - board: BOARD_RUMBA
            arduino-platform: arduino:avr
            fqbn: arduino:avr:mega
          - board: BOARD_RAMPS
            arduino-platform: arduino:avr
            fqbn: arduino:avr:mega
          - board: BOARD_SIXI_MEGA
            arduino-platform: arduino:avr
            fqbn: arduino:avr:mega
          - board: BOARD_CNCV3
            arduino-platform: arduino:avr
            fqbn: arduino:avr:mega
          - board: BOARD_WEMOS
            arduino-platform: esp8266:esp8266
            fqbn: esp8266:esp8266:lolin32
          - board: BOARD_ESP32
            arduino-platform: esp32:esp32
            fqbn: esp32:esp32:lolin32
        exclude:
          - board: BOARD_RUMBA
            robot: SIXI
          - board: BOARD_RAMPS
            robot: SIXI
            # WEMOS anything over 3 motors
          - board: BOARD_CNCV3
            robot: COREXY
          - board: BOARD_CNCV3
            robot: ZARPLOTTER
          - board: BOARD_CNCV3
            robot: SKYCAM
          - board: BOARD_CNCV3
            robot: STEWART
          - board: BOARD_CNCV3
            robot: SIXI
          - board: BOARD_CNCV3
            robot: TRADITIONAL6
          - board: BOARD_CNCV3
            robot: SCARA
            # WEMOS anything over 2 motors
          - board: BOARD_WEMOS 
            robot: COREXY
          - board: BOARD_WEMOS
            robot: ZARPLOTTER
          - board: BOARD_WEMOS
            robot: SKYCAM
          - board: BOARD_WEMOS
            robot: STEWART
          - board: BOARD_WEMOS
            robot: SIXI
          - board: BOARD_WEMOS
            robot: TRADITIONAL6
          - board: BOARD_WEMOS
            robot: SCARA
            # BOARD_ESP32 anything over 2 motors
          - board: BOARD_ESP32 
            robot: COREXY
          - board: BOARD_ESP32
            robot: ZARPLOTTER
          - board: BOARD_ESP32
            robot: SKYCAM
          - board: BOARD_ESP32
            robot: STEWART
          - board: BOARD_ESP32
            robot: SIXI
          - board: BOARD_ESP32
            robot: TRADITIONAL6
          - board: BOARD_ESP32
            robot: SCARA
            
    runs-on: windows-latest
    steps:
      # First of all, we clone the repo using the checkout action.
      - name: Checkout
        uses: actions/checkout@master
 
      # We use the arduino/setup-arduino-cli action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
      # We then install the platform, which one will be determined
      # dynamically by the build matrix.
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
          
      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./Makelangelo-firmware.ino
